spring:
  application:
    name: backend

  # MariaDB 연결 설정
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3306/account_book_db}
    username: ${SPRING_DATASOURCE_USERNAME:account}
    password: ${SPRING_DATASOURCE_PASSWORD:book}

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: none # 처음에create나 update였을 때 JPA가 테이블을 자동 생성 / none면 자동X
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
    show-sql: true

# MyBatis 설정
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: com.ohgiraffers.backend
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: account-book-jwt-secret-key-must-be-at-least-256-bits-long
  expiration: 86400000

# 서버 설정
server:
  port: 8080
